### PR TITLE
Feature/faq component

### PR DESCRIPTION
**Pull request by PriyaRajarathinam**
Problem
=======
As an engineer, I want to refractor the FAQ component.

[Link to Asana Ticket](https://app.asana.com/0/1197738625416321/1199382769817325)

Solution
========

Refactored the FAQ component by using flexbox.

Steps to Verify:
----------------
1. A setup step / beginning state
2. What to do next
3. Any other instructions
4. Expected behavior
5. Suggestions for testing

Screenshots (optional):
-----------------------
Show-n-tell images/animations here

### CODE REVIEW

**Comment by ilopezro** [comment]
This looks very much like what we had in #146. Is this PR necessary? I believe we reverted from these changes.

**Comment by PriyaRajarathinam** [comment]
> This looks very much like what we had in #129. Is this PR necessary? I believe we reverted from these changes.

I removed the scrolling from the FAQ component and on smaller screens, I removed the three-column format so that the content is easier to read

**Comment by ilopezro** [comment]
> I removed the scrolling from the FAQ component and on smaller screens, I removed the three-column format so that the content is easier to read

Ok, I'd suggest rebasing off of main as it seems like you're not up to date with `main` which might also be why you've got a ton of merge conflicts.

**Review by mocklee — APPROVED** [review]
I've just removed the hardcoded height to ease integration with the sponsor section, but this component is ready to go now!

**Pull request merged**
