### PR TITLE
fix email button & postcard on mobile

### PR DESCRIPTION
**Pull request by mocklee**
Problem
=======
As a mobile user, I find circular buttons favorable over elliptical ones

Solution
========
Unset height unit from `vh` so it doesn't shrink one-dimensionally

Screenshots (optional):
-----------------------
before:
Screenshot from 2020-11-23 23-54-17

after:
Screenshot from 2020-11-23 23-55-21

### CODE REVIEW

**Review by ilopezro — CHANGES_REQUESTED** [review]
Are these not the same commits that are already in our `main` branch?

**Comment by mocklee** [comment]
> Are these not the same commits that are already in our `main` branch? 

change is on the last commit, histories got carried over when I switched branches around on my local.

**Comment by mocklee** [comment]
rebased!

**Review by ilopezro — APPROVED** [review]
This looks amazing dude! 😍 💯

**Pull request merged**
