### PR TITLE
Code of Conduct Button

### PR DESCRIPTION
**Pull request by ilopezro**
Problem
=======
As an organization, 
we want to be MLH compliant
so we can be sponsored by MLH

[Link to Asana Ticket](https://app.asana.com/0/1197738625416321/1199397217488773/f)

Solution
========
Added the code of conduct object to `buttonProps`.

Change summary:
---------------
* added code of conduct button a6a383c

Steps to Verify:
----------------
1. Checkout branch and start local server
1. Verify that `Our Code of Conduct` button appears & that it takes you to correct link

Screenshots:
-----------------------
Screen Shot 2020-11-30 at 6 34 34 PM

### CODE REVIEW

**Review by tim-nguyen-cs — APPROVED** [review]
I'll approve it for now because it's just temporary, but I would suggest standardizing or even hardcoding the width of the button so the wrap is more consistent!

**Comment by ilopezro** [comment]
Screen Shot 2020-11-30 at 8 25 40 PM
@tim-nguyen-cs thoughts?

**Comment by tim-nguyen-cs** [comment]
It works for now - thanks for making that update! We should have a newer iteration of the site ou by this weekend anyway.

**Comment by ilopezro** [comment]
In order to fix some issues with mobile responsiveness, we have opted to put in two sets of buttons. 

**Issue with mobile**
Screen Shot 2020-11-30 at 9 12 46 PM

**Fix **
Screen Shot 2020-11-30 at 11 48 07 PM

**Pull request merged**
