### PR TITLE
Email Icons Changes

### PR DESCRIPTION
**Pull request by ilopezro**
Problem & Solution 
=======
In order to prevent dependency on external links, we can use [Material Design Icons](https://dev.materialdesignicons.com/getting-started/react) React components. I've used their `Icon` component along with their SVG images of the icons used!

### CODE REVIEW

**Review by tim-nguyen-cs — APPROVED** [review]
Not sure if we are 110% with MatDesign, but looks great to me!

**Comment by ilopezro** [comment]
@tim-nguyen-cs the reason why I used Material Design is because your image source was `https://icongr.am/material/check-circle-outline.svg?size=25&color=4f728e`. So although we were grabbing from [IconGram](https://www.icongr.am/) to grab the Icon, the icons came directly from Material Design.

**Comment by tim-nguyen-cs** [comment]
@ilopezro I understand that. What I'm saying is that I'm not sure what icon library we should be using specifically - it's more so a parenthetical comment versus a comment against your PR. Hope this clarifies it!

**Comment by ilopezro** [comment]
@tim-nguyen-cs ahh ok gotcha! I'm totally okay using this library 👍🏽

**Pull request merged**
